---

- block:
    - name: get checksum list
      set_fact:
        __prometheus_checksums: "{{ lookup('url', 'https://github.com/prometheus/node_exporter/releases/download/v' + node_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"

    - name: get checksum for {{ go_arch }} architecture
      set_fact:
        __prometheus_checksum: "{{ __prometheus_checksums | node_exporter_checksum('linux', go_arch) }}"
  become: false
  delegate_to: localhost
  run_once: true

- name: download node_exporter binary archive
  become: false
  delegate_to: "{{ node_exporter_delegate_to }}"
  run_once: "{{ 'false' if node_exporter_direct_download else 'true' }}"
  get_url:
    url: "{{ node_exporter_release_download_url }}/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ node_exporter_local_tmp_directory }}/node_exporter-linux-amd64.tar.gz"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract node_exporter archive
  become: false
  delegate_to: "{{ node_exporter_delegate_to }}"
  run_once: "{{ 'false' if node_exporter_direct_download else 'true' }}"
  unarchive:
    src: "{{ node_exporter_local_tmp_directory }}/node_exporter-linux-amd64.tar.gz"
    dest: "{{ node_exporter_local_tmp_directory }}"
    copy: false
  register: _extract_archive

...
