---

- name: prepare
  include_tasks: prepare.yml

- name: download archive
  include_tasks: download.yml
  #when:
  #  - not stat_node_exporter_binary.stat.exists

- name: install
  include_tasks: install.yml
  #when:
  #  - not stat_node_exporter_binary.stat.exists

- name: configure
  include_tasks: configure.yml

- name: service
  include_tasks: service.yml

...
