---

- name: restart node_exporter
  become: true
  ansible.builtin.service:
    name: node_exporter
    state: restarted

- name: reload node_exporter
  become: true
  ansible.builtin.service:
    name: node_exporter
    state: reloaded

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
